services:
  postgres:
    image: postgres:15
    container_name: postgres-iam
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${PGTZ}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d:ro
    networks:
      iam-net:
        ipv4_address: 172.25.0.15

  service-registry:
    build:
      context: ./discovery_server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      iam-net:
        ipv4_address: 172.25.0.14

  api-gateway:
    build:
      context: ./api_gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
    depends_on:
      - service-registry
    networks:
      iam-net:
        ipv4_address: 172.25.0.13

  iam-service:
    build:
      context: ./iam_service
      dockerfile: Dockerfile
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      JWT_SECRET: ${JWT_SECRET}
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      APP_ENCRYPTION_KEY: ${APP_ENCRYPTION_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      ALLOWED_IPS: ${ALLOWED_IPS}
    depends_on:
      - postgres
      - service-registry
    networks:
      iam-net:
        ipv4_address: 172.25.0.10

  frontend:
    build:
      context: ../laboratory-iamservice-frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - iam-service
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_GOOGLE_CLIENT: ${VITE_GOOGLE_CLIENT}
    networks:
      iam-net:
        ipv4_address: 172.25.0.11

  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      iam-net:
        ipv4_address: 172.25.0.17
    volumes:
      - mongo-data:/data/db

  notification-service:
    build:
      context: ./notification_service
      dockerfile: Dockerfile
    ports:
      - "7070:7070"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      ALLOWED_ORIGIN: ${ALLOWED_ORIGIN}
      ALLOWED_PORT: ${ALLOWED_PORT}
      APP_ENCRYPTION_KEY: ${APP_ENCRYPTION_KEY}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      iam-net:
        ipv4_address: 172.25.0.12

  redis:
    image: redis:7
    container_name: redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    ports:
      - "6379:6379"
    networks:
      iam-net:
        ipv4_address: 172.25.0.16
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./redis/data:/data  # persist data
    healthcheck:
      test: [ "CMD", "redis-cli", "PING" ]
      interval: 5s
      timeout: 3s
      retries: 5

  broker:
      image: apache/kafka:latest
      container_name: broker
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
        KAFKA_NUM_PARTITIONS: 3
      networks:
        iam-net:
          ipv4_address: 172.25.0.20

networks:
  iam-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  postgres-data:
  mongo-data: