services:
  postgres:
    image: postgres:15
    container_name: postgres-iam
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password_here
      POSTGRES_DB: iam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
#      - ./postgres-init:/docker-entrypoint-initdb.d:ro  --> entry point for db schema
    networks:
      - iam-net

  iam-service:
    build:
      context: ./iam_service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - postgres
    networks:
      - iam-net

networks:
  iam-net:
    driver: bridge

volumes:
  postgres-data: