server:
  port: 8089
  address: ${ALLOWED_PORT}   # <== Listen on all interfaces (NOT just localhost)
  error:
    include-message: always

spring:
  application:
    name: iam-service
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: redis
    port: 6379
  mail:
    username: ${MAIL_USERNAME:no-reply@dummy.local}
    password: ${MAIL_PASSWORD:dummy-password}
  kafka:
    bootstrap-servers: 34.199.182.98:9092
    properties:
      security.protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: iam-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

google:
  web-client-id: 757411247793-11ciuarrirqp0m07eqhq8uubvgpdhois.apps.googleusercontent.com
eureka:
  client:
    register-with-eureka: true      # Cho phép đăng ký với Eureka
    fetch-registry: true            # Cho phép lấy danh sách các service khác
    service-url:
#      defaultZone: http://23.23.152.34:8761/eureka/ -> cho deploy register server
      defaultZone: https://discovery-server-zsph.onrender.com/eureka
  instance:
    prefer-ip-address: true         # Dùng IP thay vì hostname (tránh lỗi trong Docker)
    instance-id : iam-service:8089
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

app:
  email:
    from: "no-reply@lab-iam.local"

