server:
  port: 7070
  address: ${ALLOWED_PORT}   # <== Listen on all interfaces (NOT just localhost)

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017/?authSource=admin
      database: NotificationDB
      mapping:
        type-key: null

  mail:
    username: ${MAIL_USERNAME:no-reply@dummy.local}
    password: ${MAIL_PASSWORD:dummy-password}
  kafka:
    bootstrap-servers: broker:9092
    properties:
      security.protocol: PLAINTEXT
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 1000
      max-poll-records: 10
#eureka:
#  client:
#    service-url:
#      defaultZone: https://discovery-server-zsph.onrender.com/eureka/
#    registry-fetch-interval-seconds: 30
#
#  instance:
#    prefer-ip-address: false
#
#    hostname: 35.172.58.177
#
#    instance-id: ${spring.application.name}:${eureka.instance.hostname}:${server.port}
#
#    non-secure-port: ${server.port}
#    non-secure-port-enabled: true
#
#    health-check-url: http://${eureka.instance.hostname}:${server.port}/actuator/health
#    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator/info
#    home-page-url: http://${eureka.instance.hostname}:${server.port}/
#
#    lease-renewal-interval-in-seconds: 30
#    lease-expiration-duration-in-seconds: 90
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://service-registry:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: notification-service:7070
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

app:
  email:
    from: "no-reply@lab-iam.local"

